import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AuthContextProvider } from "@/contexts/AuthContext";
import { SocketContextProvider } from "@/contexts/SocketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <SocketContextProvider>
            <Toaster />
            <div className="p-4 h-screen flex items-center justify-center">
              {children}
            </div>
          </SocketContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
